project:
    path:     /
    defaults: { _controller: "EstimationsMainBundle:Project:index" }

project_show:
    path:     /{id}/show
    defaults: { _controller: "EstimationsMainBundle:Project:show" }

project_new:
    path:     /new
    defaults: { _controller: "EstimationsMainBundle:Project:new" }

project_create:
    path:     /create
    defaults: { _controller: "EstimationsMainBundle:Project:create" }
    requirements: { _method: post }

project_edit:
    path:     /{id}/edit
    defaults: { _controller: "EstimationsMainBundle:Project:edit" }

project_update:
    path:     /{id}/update
    defaults: { _controller: "EstimationsMainBundle:Project:update" }
    requirements: { _method: post|put }

project_delete:
    path:     /{id}/delete
    defaults: { _controller: "EstimationsMainBundle:Project:delete" }
    requirements: { _method: post|delete }

issue_new:
    path:     /{projectId}/issues/new
    defaults: { _controller: "EstimationsMainBundle:Issue:new" }

issue_create:
    path:     /{projectId}/issues/create
    defaults: { _controller: "EstimationsMainBundle:Issue:create"}

#issue:
#    path:     /
#    defaults: { _controller: "EstimationsMainBundle:Issue:index" }
#
#issue_show:
#    path:     /{id}/show
#    defaults: { _controller: "EstimationsMainBundle:Issue:show" }
#
#issue_new:
#    path:     /new
#    defaults: { _controller: "EstimationsMainBundle:Issue:new" }
#
#issue_create:
#    path:     /create
#    defaults: { _controller: "EstimationsMainBundle:Issue:create" }
#    requirements: { _method: post }
#
#issue_edit:
#    path:     /{id}/edit
#    defaults: { _controller: "EstimationsMainBundle:Issue:edit" }
#
#issue_update:
#    path:     /{id}/update
#    defaults: { _controller: "EstimationsMainBundle:Issue:update" }
#    requirements: { _method: post|put }
#
#issue_delete:
#    path:     /{id}/delete
#    defaults: { _controller: "EstimationsMainBundle:Issue:delete" }
#    requirements: { _method: post|delete }
