project:
    path:     /
    defaults: { _controller: "EstimationsMainBundle:Project:index" }

project_show:
    path:     /{id}/show
    defaults: { _controller: "EstimationsMainBundle:Project:show" }

project_new:
    path:     /new
    defaults: { _controller: "EstimationsMainBundle:Project:new" }

project_create:
    path:     /create
    defaults: { _controller: "EstimationsMainBundle:Project:create" }
    requirements: { _method: post }

project_edit:
    path:     /{id}/edit
    defaults: { _controller: "EstimationsMainBundle:Project:edit" }

project_update:
    path:     /{id}/update
    defaults: { _controller: "EstimationsMainBundle:Project:update" }
    requirements: { _method: post|put }

project_delete:
    path:     /{id}/delete
    defaults: { _controller: "EstimationsMainBundle:Project:delete" }
    requirements: { _method: post|delete }

project_calculate_average:
    path:     /{id}/calc
    defaults: { _controller: "EstimationsMainBundle:Project:calculateAverage" }

issue_new:
    path:     /{projectId}/issues/new
    defaults: { _controller: "EstimationsMainBundle:Issue:new" }

issue_create:
    path:     /{projectId}/issues/create
    defaults: { _controller: "EstimationsMainBundle:Issue:create"}

project_estimate:
    path:     /{id}/estimate
    defaults: { _controller: "EstimationsMainBundle:Project:estimate" }

project_import:
    path:     /{id}/load
    defaults: { _controller: "EstimationsMainBundle:Project:load" }

project_import_issues:
    path:     /{id}/load/issues
    defaults: { _controller: "EstimationsMainBundle:Project:loadIssues" }