project:
    resource: "@EstimationsMainBundle/Resources/config//routing/project.yml"
    prefix:   /project
main:
    resource: "@EstimationsMainBundle/Resources/config//routing/main.yml"
    prefix:   /